### ISSUE TITLE
Is it a dead project?

### ISSUE THREAD

**Issue by prochac** [codelessarchitecture/codelessarchitecture-spec#1]
The only activity hare was deletion of release target.

https://github.com/codelessarchitecture/codelessarchitecture-spec/commit/73a42fb531d14852eb9d399874fd0529c8f78f3f

**Comment by prochac** [comment]
This repo is a proof of your empty claim from website

```
Locked-in → Liberated 
The “codeless definition” is an open standard that can be easily ported to any compatible development framework of your choosing. That means no more vendor lock-in. Find the development technologies that are best for your organization.
```
https://www.codelessarchitecture.org/#hs_cos_wrapper_widget_1646939914234

**Comment by mhassan1** [comment]
Thanks for the feedback. The spec is in progress, and we will publish it here once it is ready.
